### ISSUE TITLE
Install does not work with python3

### ISSUE THREAD

**Issue by SylvainLan** [KamitaniLab/bdpy#1]
Hi, 

I have done the install based on what's written on the README with python2.7 and then python3, the same way for both. 

It works perfectly with python2.7 but with python3 I get the following error when trying to import:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sylvain/.local/lib/python3.5/site-packages/bdpy/__init__.py", line 10, in <module>
    from bdata import BData
ImportError: No module named 'bdata'

**Comment by ShuntaroAoki** [comment]
Thank you for the report.
Actually, our python packages do not yet support Python 3 because our lab still relies on Python 2. We're working on the Python 3 compatibility. At this moment, please try our code with Python 2.
