### ISSUE TITLE
fig list is not work

### ISSUE THREAD

**Issue by kencan7749** [KamitaniLab/bdpy#11]
https://github.com/KamitaniLab/bdpy/blob/929a720f28e7b42e53ac6550271d82b2c1fbd7bb/bdpy/fig/fig.py#L158

In this line, returned variable `fig` is just the last element of the fig_list.  If iterate fig list, it will be better to return the list of each figure.

**Comment by ShuntaroAoki** [comment]
Fixed.
Thank you!
